# -*- coding: utf-8 -*-
"""optantra

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1dSUri7qxmUwYr-b0Z0lVjPde0dULjkMh
"""

!pip install -q streamlit
print("✅ Streamlit instalado")

procesos = [
    "Recibo y entrada de mercancía",
    "Control y planeación del inventario",
    "Compras y gestión de proveedores",
    "Alistamiento y despacho de pedidos",
    "Atención al cliente / PQRS",
    "Tareas administrativas internas",
    "Reportes, indicadores y análisis",
    "Otro"
]

proceso_elegido = procesos[2]

descripción=  "el producto se agota cada 3 semanas"
urgencia ="Alta"

if proceso_elegido == procesos[1]:
  sugerencia = "Implementa una regla mínimo-máximo y una alerta semanal."
elif proceso_elegido == procesos[2]:
  sugerencia = "reconsidera los metodos de pago y los tiempos de entrega."
else:
   sugerencia = "Audita y documenta el flujo para detectar cuellos de botella."

print(f"""
🔍 Proceso:   {proceso_elegido}
✍️  Problema: {descripción}
⚡ Urgencia:  {urgencia}

💡 Sugerencia automática:
{sugerencia}
""")

# 📁 Código para crear el archivo 1stapp.py

code = """
import streamlit as st

st.set_page_config(page_title='Optantra | Internal Process Advisor', layout='centered')
st.title('🚀 Optantra | Asistente de Procesos Internos')
st.write('Optimiza desde adentro. Describe un proceso y te ayudamos a mejorarlo.')

procesos = [
    'Recibo y entrada de mercancía',
    'Control y planeación del inventario',
    'Compras y gestión de proveedores',
    'Alistamiento y despacho de pedidos',
    'Atención al cliente / PQRS',
    'Tareas administrativas internas',
    'Reportes, indicadores y análisis',
    'Otro'
]

proceso = st.selectbox('🛠️ Selecciona el proceso', procesos)
descripcion = st.text_area('📝 Describe el problema:')
urgencia = st.radio('⚡ Nivel de urgencia', ['Baja','Media','Alta'])

if st.button('💡 Obtener sugerencia'):
    if not descripcion.strip():
        st.warning('⚠️ Describe el problema para poder ayudarte.')
    else:
        if proceso == 'Control y planeación del inventario':
            sugerencia = 'Implementa una regla mínimo-máximo y alerta semanal.'
        elif proceso == 'Recibo y entrada de mercancía':
            sugerencia = 'Digitaliza la inspección de calidad con un checklist.'
        else:
            sugerencia = 'Revisa y estandariza el flujo de trabajo.'

        st.success(f'''
        🧩 Proceso: {proceso}
        ✍️ Descripción: {descripcion}
        ⚡ Urgencia: {urgencia}

        ✅ Sugerencia:
        {sugerencia}
        ''')
"""

# ✅ Guardar el código en un archivo .py dentro de Colab
with open("1stapp.py", "w", encoding="utf-8") as f:
    f.write(code)

print("✅ Archivo 1stapp.py creado exitosamente.")